# Pipeline resource configuration
pivnet_token: NRWrckqpyXxiwLJ2XBMf
opsman_major_minor_version: ^1\.12\..*$ # PCF Ops Manager minor version to track
ert_major_minor_version: ^1\.12\..*$ # PCF Elastic Runtime minor version to track
git_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEAyBbIyfkbWzgnvN9TBJa7C6inrLbHnfLlOJjbapqdX6T4qGaA
  zq+4K7/nN7GJTFl7oqXj3Soe8XG8yW8mcmTMK0VWzLUuo6e0xsEaM/00oN9UUccM
  7UwOO59m8k0XALMyF2Afg8VVRJ0kH7HKpdh96l9ZSb75JpvHKbl5ZZMiMWKFIwQ/
  REDASywPPufDm826ILU7nfZAafyxdQNuagYtkqG95/UOgE7d7MFAQihB+DoSu9SH
  GSybts4Z9ZD+taqTESaYomifIQt4qbdK8oEQbp9LpLbuSgNsGW/Q227Hld07rFkc
  EMy02NE9sJO3uoUophbP7m+WBmHbHA0lf6ZwZe+ZBierJMhc5uezq08frVEF/SZw
  mZsyM3DPNFQnM8gt2Vf27yhTj4hKjJIR+Kroc9RdhUi6fz7g3k2KEDKwVTb0kA4h
  UWUavsry2LzYTnK9R1SlrYayLigxCAWqoN0DnoiQ2bsKNzOhJnbY1iQRNdcjbWLM
  lN8iH7WajJVxarEcq73pP1jSxEOSUw7CRr1dj95Tv6D/B5fkUZzctVMNv+I+wavP
  6xbK2CTMjg9KfbJk7ATl8XS38EdGARXWZg7a7zuRYJrdysgBZW9ZVo+dQrpUY+hl
  YkhNPHgn1Uk4/eqnGjEXDOWJrBgsesO+i2iE2laR+Qmz+QVXflKcyC6cxe8CAwEA
  AQKCAgBVQ1hGsO9WXMSaOHQw9WY5XqIs+CpyBSpmhsShVceQFUWcxSlIahrKEdme
  ovnF3i/QLG7ANQ3Ah14SXFn+zzMtkTueuepo9LMVKv5WfySpFOHigzbf+9Po1lFR
  GUafFr1WtrBXP4TJW0kkdGfNakal1AHBai7To/gnsJCplxwv/TKMrGelVw5aOik4
  /hwdzXnuLCx+cIwcXgDkwxSO+5j57hB1wrhuNq1dETCnwG30MBMBlVwIfzjPml33
  hdT0Zv6KhW7vbjO5KiE9+Qxn8FWnPhxG0WkTgwfSgxJ2H2vPUdn25HYQNpst9WQb
  VacqRUoAFKKAkW5Vw+dRucxr6+ni1KWqZ2QxQVGf+GI7XrAYCpSaKpHVwKabzc2z
  R/kYrKSTpYWmpBJXTZr+U6FLqgMGyao1MAFuypTP0l7wyp7kJXa3o0Jne24EU8C+
  Tn4GNNl77PJPR5sbGTPWN0lEayxANjwYy1oEJS58imXtPGSxtgj4OU8usAnPJVtx
  ZXKhOl6CAn5KZ1mlGu0TDz6qtXSxH7GoDWvSnGMiDVtcVVhjMJpyqbBmF7c7POiF
  1rrNxvOSMyuxa8k2E6kkMLjwREwBI7PqBrXbHYLvn09EGQxUEij2LV6GzNPPuhCj
  6OTTta8kXiat82BPPvxj8j58p9mKcQjn0ZuT/F9pgCh5nhSx6QKCAQEA9zngb7Ty
  ggGC9wItq5gcYVIb+1sxVvK7hkd4UduRu2rBEssOhC/Y1Kkp1+NvmSXg7TJYDTAy
  XwONaaknAEP45Q58y/314NNcA8bz5ry/nPPy2EnrVF805wCWDox1hDQzlfht8TuY
  56D4eLc+ABtd8oWf8qV7hbnh6DxM6S+B5yG33aaLEW8TL167g4xvlUCuqeh5SVLS
  d6j8Ow/tM2MrIfr8Hz0W6rd/xHz5yhYWnzO07k2bzcfIuo/VQXaWzHnuWxE+fyVg
  YElLl4Vxkh5D9HEQjEPt0stHrMRLqleOXRvHLllMPh9RkCEo8CtuCcM9H0N7mxX4
  2VVEXdixSKPl+wKCAQEAzzCnMHi5ngdpPQ9Ji3sca7IKE/S03mSNjhjhSwxsGxsT
  HhmWnOzpT9RHtQY8VOZ0UP1fK83s4UxUs6w6ZBUfbAHEXpUJa7du72wK1JU7JydF
  42sJmOMtuOq1tzZDI8iYG5hwadU5GBVk4mERelbdArRjEtvixLMTvl2uwbLBTHGo
  ne+zPw5vzBXDcxqwXvs5JadGBVs6ZRXrgrt39DWUsjTMx8pMgM0JYDZTu+rfFqBo
  E+kBeoKc7l9KQVtMtp68zquyNo/MofuKH9oYvisQNCU7REEGD36POALynJwTFUlz
  k9dkGxtP6eJkBEO2lIkuT7SQKgvU0EhRCr0pU9xBnQKCAQBmB53HnE7lNoh9Nonw
  omM8Cu3/a2BOePjJbx+J8OsRBPrPrbu89B4xjer17Sg2dTqByeAq+TQgoE+xRp0Q
  7/x9U+BPM+1QrwnviSFJnaYauVcEymTzuiMUHtrPAErTl9OeVhvRjf4JwhYpg75z
  vtej6l/bfU4gH1nLRW+cYP3kjLbcJAqK1GN/jkInBUNbvokXGBlOGH9B4RzPp0AG
  kCvR50o7/jNCBR8W0VkpfLozU9yc6KyfXY9K52dkj/OmScAEF3bKdHt04WrwCqOX
  YSQ8cpkYukQhVcGr3Is5rs7TQE6Qo0vi63v21qiVjebo4omMKIaPt56u2xDPBkoM
  J5AXAoIBAQCvRBn6L/XdD6nfpCHzotYc6EQMM5IZGvh//t3+TWjZ2SJn8P9uih6n
  kAyEvtykeTpmFJ/Af3dl8tsoDoZqiU/GXwxNckfA3jAyyrOytvaOHXPKeI5qzaqs
  5aeIb5eGGrdJiL93V47vp5FqyvAtDHPzSMMSff2rpU0LWVZutpc74l3gFJgNvFmo
  S7TFlwshneTuzDy4ZT7VqiBKu+kyJW0+/tlIHQJwZoIK6IoWyg2jp1fDl/TPPNQh
  9WvsM56GUWuobKfZ7fUOBaoHXchWfjk70076YwMMcmQW3q96+bBO7o6dvrQJFiaY
  1BEFZn550j3h4P2fA9knxDUCH5hpP0YlAoIBAHyTvJNMAGvSVxZg6WLfOOBziFHX
  S1gwFP09vffggTwvhk7kB7zD4lyGvgohq79SZEmfj/gMpPcmOhr+PrunjZqnKSS0
  eAdBYylDDmD+WRrrxCRYg14IejbzqZufH38mpgqb0oXIfVvn3np6sL4n7KNhbjgJ
  NExrvNtaOj8HuUjvxmNcOSlmjOlAxRDCr1FYt3slVPVouGv78avWdIEY/p4sEAco
  +AY/sK+DTEdks1qGkt6z477FOtYvnNy3Z6oXG2gu3/ZgWwkHZNRsAcZqsJcZHCE/
  TECdaQ3DuCl9P4qnUy3A5VRTwzUofQ3iEcgSSH97pihAXAib5cml+OqdxGA=
  -----END RSA PRIVATE KEY-----

# vCenter configuration
vcenter_host: 192.168.1.51             # vCenter host or IP
vcenter_usr: administrator@vsphere.local  # vCenter username. If user is in a domain, then escape the \, example `domain\\user`
vcenter_pwd: Pivotal!123            # vCenter password
vcenter_data_center: Datacenter     # vCenter datacenter

# Ops Manager VM configuration
om_vm_host: esxi.mypcf.net          # Optional - vCenter host to deploy Ops Manager in
om_data_store: datastore1           # vCenter datastore name to deploy Ops Manager in
opsman_domain_or_ip_address: opsmgr.mypcf.net  # FQDN to access Ops Manager without protocol (will use https), ex: opsmgr.example.com
opsman_admin_username: admin        # Username for Ops Manager admin account
opsman_admin_password: pivotal!123  # Password for Ops Manager admin account
om_ssh_pwd: pivotal!123             # SSH password for Ops Manager (ssh user is ubuntu)
om_decryption_pwd: Pivotal!123      # Decryption password for Ops Manager exported settings
om_ntp_servers: time.google.com     # Comma-separated list of NTP Servers
om_dns_servers: 192.168.1.1,8.8.8.8 # Comma-separated list of DNS Servers
om_gateway: 192.168.1.1             # Gateway for Ops Manager network
om_netmask: 255.255.255.0           # Netmask for Ops Manager network
om_ip: 192.168.1.52                 # IP to assign to Ops Manager VM
om_vm_network: VM Network           # vCenter network name to use to deploy Ops Manager in
om_vm_name: OpsMgr-1.12.latest      # Name to use for Ops Manager VM
opsman_disk_type: "thin"            # Disk type for Ops Manager VM (thick|thin)
om_vm_power_state: true             # Whether to power on Ops Manager VM after creation

# vCenter Cluster or Resource Pool to use to deploy Ops Manager.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
om_resource_pool: /Datacenter/host/Cluster

ephemeral_storage_names: datastore1    # Ephemeral Storage names in vCenter for use by PCF
persistent_storage_names: datastore1   # Persistent Storage names in vCenter for use by PCF

bosh_vm_folder: "pcf_vms"              # vSphere datacenter folder (such as pcf_vms) where VMs will be placed
bosh_template_folder: "pcf_templates"  # vSphere datacenter folder (such as pcf_templates) where templates will be placed
bosh_disk_path: "pcf_disk"             # vSphere datastore folder (such as pcf_disk) where attached disk images will be created

trusted_certificates:         # Trusted certificates to be deployed along with all VM's provisioned by BOSH
vm_disk_type: "thin"          # Disk type for BOSH provisioned VM. (thick|thin)

# AZ configuration for Ops Director
az_1_name: az1                         # Logical name of availability zone. No spaces or special characters.
az_1_cluster_name: Cluster             # Name of cluster in vCenter for AZ1
az_1_rp_name:                          # Resource pool name in vCenter for AZ1

ntp_servers: time.google.com           # Comma-separated list of NTP servers to use for VMs deployed by BOSH
ops_dir_hostname: mybosh.mypcf.net     # Optional DNS name for Ops Director. Should be reachable from all networks.
enable_vm_resurrector: true            # Whether to enable BOSH VM resurrector
max_threads: 30                        # Max threads count for deploying VMs

# Network configuration for Ops Director
icmp_checks_enabled: false    # Enable or disable ICMP checks

infra_network_name: "INFRASTRUCTURE"
infra_vsphere_network: VM Network      # vCenter Infrastructure network name
infra_nw_cidr: 192.168.1.0/24          # Infrastructure network CIDR, ex: 10.0.0.0/22
infra_excluded_range: 192.168.1.1-192.168.1.52,192.168.1.63-192.168.1.255  # Infrastructure network exclusion range
infra_nw_dns: 192.168.1.1,8.8.8.8      # Infrastructure network DNS
infra_nw_gateway: 192.168.1.1          # Infrastructure network Gateway
infra_nw_azs: az1                      # Comma separated list of AZ's to be associated with this network
nsx_networking_enabled: false          # (true|false) to use nsx networking feature
nsx_address:                           # address of nsx
nsx_username:                          # username for nsx access
nsx_password:                          # password for nsx access
nsx_ca_certificate:                    # cert for nsx

deployment_network_name: "DEPLOYMENT"
deployment_vsphere_network: VM Network # vCenter Deployment network name
deployment_nw_cidr: 192.168.1.0/24     # Deployment network CIDR, ex: 10.0.0.0/22
deployment_excluded_range: 192.168.1.1-192.168.1.62,192.168.1.163-192.168.1.255   # Deployment network exclusion range
deployment_nw_dns: 192.168.1.1,8.8.8.8 # Deployment network DNS
deployment_nw_gateway: 192.168.1.1     # Deployment network Gateway
deployment_nw_azs: az1                 # Comma separated list of AZ's to be associated with this network

services_network_name: "SERVICES"
is_service_network: false              # Required select service network option in Ops man true or false
services_vsphere_network: VM Network   # vCenter Services network name
services_nw_cidr: 192.168.1.0/24       # Services network CIDR, ex: 10.0.0.0/22
services_excluded_range: 192.168.1.1-192.168.1.162,192.168.1.196-192.168.1.255    # Services network exclusion range
services_nw_dns: 192.168.1.1,8.8.8.8   # Services network DNS
services_nw_gateway: 192.168.1.1       # Services network Gateway
services_nw_azs: az1                   # Comma separated list of AZ's to be associated with this network

dynamic_services_network_name: "DYNAMIC-SERVICES"
dynamic_services_vsphere_network: VM Network   # vCenter Dynamic Services network name
dynamic_services_nw_cidr: 192.168.1.0/24       # Dynamic Services network CIDR, ex: 10.0.0.0/22
dynamic_services_excluded_range: 192.168.1.1-192.168.1.195,192.168.1.230-192.168.1.255    # Dynamic Services network exclusion range
dynamic_services_nw_dns: 192.168.1.1,8.8.8.8   # Dynamic Services network DNS
dynamic_services_nw_gateway: 192.168.1..1      # Dynamic Services network Gateway
dynamic_services_nw_azs: az1                   # Comma separated list of AZ's to be associated with this network

ert_singleton_job_az: az1              # AZ to use for deployment of ERT Singleton jobs
ert_errands_to_disable:                # Comma-separated list of errand names to disable before deploy

loggregator_endpoint_port:             # Loggegrator Port. Default is 443
company_name: BuschLab                 # Company Name for Apps Manager
company_proxy_domain:                  # If set to a non-empty string, bypass DNS when uploading stemcells to Ops Manager

## Syslog endpoint configuration goes here
# Optional. If syslog_host is specified, syslog_port, syslog_protocol,
# syslog_drain_buffer_size, and enable_security_event_logging must be set.
syslog_host:
syslog_port:
syslog_protocol:
enable_security_event_logging: false
syslog_drain_buffer_size: 10000

## Wildcard domain certs go here
# Optional. Will be generated if blank.
ssl_cert:
ssl_private_key:
saml_ssl_cert:
saml_ssl_private_key:

haproxy_forward_tls: disable # If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_backend_ca:          # HAProxy will use the CA provided to verify the certificates provided by the router.

# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
router_tls_ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384 
haproxy_tls_ciphers: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384

disable_http_proxy: false
security_acknowledgement: X  # Must be set to 'X'. See explanation here: https://docs.pivotal.io/pivotalcf/latest/customizing/config-er-vmware.html#app-security

## TCP routing and routing services
tcp_routing: disable                    # Enable/disable TCP routing (enable|disable)
tcp_routing_ports:                      # A comma-separated list of ports and hyphen-separated port ranges, e.g. 52135,34000-35000,23478
route_services: disable                 # Enable/disable route services (enable|disable)
ignore_ssl_cert_verification: true      # Whether to disable SSL cert verification for this environment
garden_network_pool_cidr: 10.254.0.0/22 # Only change this if you need to avoid address collision with a third-party service on the same subnet.
garden_network_mtu: 1454                # Applications Network Maximum Transmission Unit bytes

# If smtp_address is configured, smtp_from, smtp_port, smtp_user, smtp_pwd, and
# smtp_auth_mechanism must also be set.
smtp_address: smtp.sendgrid.net
smtp_from: donotreply@mypcf.net
smtp_port: 587
smtp_user: chriscbusch
smtp_pwd: muck2016
smtp_auth_mechanism: plain # (none|plain|cram-md5)

## Authentication type needed. SAML is not presently supported.
authentication_mode: internal # (internal|ldap) If ldap, specify ldap configuration below.
ldap_url:
ldap_user:
ldap_pwd:
search_base:
search_filter:
group_search_base:
group_search_filter:
mail_attribute_name:
first_name_attribute:
last_name_attribute:

## Deployment domain names
system_domain: system.mypcf.net
apps_domain: apps.mypcf.net

skip_cert_verify: true       # If true, disable SSL certificate verification for this environment.

disable_insecure_cookies: false # If true, disable insecure cookies on the router.

default_quota_memory_limit_mb: 10240
default_quota_max_number_services: 1000
allow_app_ssh_access: false             # Whether to allow SSH access to application instances

router_request_timeout_in_seconds: 900

ha_proxy_ips: 192.168.1.162   # Comma-separated list of static IPs
router_static_ips:            # Comma-separated list of static IPs
tcp_router_static_ips:        # Comma-separated list of static IPs
ssh_static_ips:               # Comma-separated list of static IPs

mysql_monitor_email: chriscbusch@gmail.com   # Email address to receive MySQL monitor notifications
mysql_backups: disable                       # Whether to enable MySQL backups. (disable|s3|scp)

#SCP backup config params (leave empty values if you're not using scp)
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

## Default resource configuration
## these resources can take any parameter made available in 
## the ops manager API ( https://<your-ops-man/docs#configuring-resources-for-a-job )
consul_server_instances: 1
nats_instances: 1
etcd_tls_server_instances: 1
nfs_server_instances: 1
mysql_proxy_instances: 1
mysql_instances: 1
backup_prepare_instances: 0
ccdb_instances: 0
diego_database_instances: 1
uaadb_instances: 0
uaa_instances: 1
cloud_controller_instances: 1
ha_proxy_instances: 1
router_instances: 1
mysql_monitor_instances: 1
clock_global_instances: 1
cloud_controller_worker_instances: 1
diego_brain_instances: 1
diego_cell_instances: 3
loggregator_traffic_controller_instances: 1
syslog_adapter_instances: 1
doppler_instances: 1
tcp_router_instances: 0

# leave nsx fields empty if you are not leveraging the nsx features for a given component
tcp_router_nsx_security_group:
tcp_router_nsx_lb_edge_name:
tcp_router_nsx_lb_pool_name:
tcp_router_nsx_lb_security_group:
tcp_router_nsx_lb_port:
router_nsx_security_group:
router_nsx_lb_edge_name:
router_nsx_lb_pool_name:
router_nsx_lb_security_group:
router_nsx_lb_port:
diego_brain_nsx_security_group:
diego_brain_nsx_lb_edge_name:
diego_brain_nsx_lb_pool_name:
diego_brain_nsx_lb_security_group:
diego_brain_nsx_lb_port:
